### ISSUE TITLE
Replaced zim files fail to load (Internal Server Error)

### ISSUE THREAD

**Issue by epheterson** [DocDrydenn/kiwix-zim#4]
Not sure why yet, but my newly-replaced zims no longer load:

```
Internal Server Error

An internal server error occured. We are sorry about that :/

error 2 opening file "/data/wikipedia_en_all_maxi_2021-12.zim
```

**Comment by epheterson** [comment]
Looks like, for some reason, if you're running kiwix in a docker instance then the container needs to be relaunched before the files load successfully. Could you add an option to relaunch docker iff any zim files are updated? I could add it to my run script (i.e. restart every time) but that's unnecessary since updates are relatively rare. 

All you'd need is to know the docker container name and run:
`docker restart my_container`

**Comment by DocDrydenn** [comment]
Dang! Glad to hear it wasn't my script, although I don't see how it could have been.

As for your request, I've tossed it around in my head since I started this project. The major issue isn't that it can't be coded, it's having to figure out (out of a countless number of different ways) someone's specific setup is done.

Your setup is in a container. My setup is a VM. The ZIM(s) might reside on the local machine or on a remote share.... the point is that this will be a nightmare to try to account for. 

Another aspect to take account of is where the download (via this script) is initiated. Running this script on my Kiwix VM means that my VM will do the download, but the writing of the files must cross back to the share, but if I run the script on my share's host machine (no Kiwix setup there), then the host machine does the downloading and the writing is once... but, I now have to find a way to tell Kiwix-server (running on a VM) that something was done to the ZIM(s) and it needs to update/restart/etc.. Just talking about this is making my head hurt. Ugh.

Anyway, I think you get my point. Again, not saying it can't be done, just saying what a nightmare this would be.

I think the best thing for this "post-processing" sorta of thing, is probably to leave it to the individual to take care of.

If everything is in the same spot, one could create their own personal post script and just "and" (`&&`) it to the end of this script's command. For example something like this: `./kiwix-zim.sh /opt/kiwix-zim/data/ -d && /opt/kiwix-post.sh`

I know this isn't the kind of answer you were looking for and I do thank you for your suggestions, however, I just don't think I want to put something this complex into this little script.

**Comment by epheterson** [comment]
Yeah I get your hesitation, do you know of a way I can execute my post command iff the script updates a container? Or maybe you could have an argument that is a full path to a script to run after?

**Comment by DocDrydenn** [comment]
I'm not a docker user, or know the specifics of how you have everything setup... but if it is as simple as you mentioned above, then this should do it. Just change `my_container` to the name of yours?

`restart_container.sh`
```BASH
#!/bin/bash
docker restart my_container
exit 0
```

Again, not a docker user, so I won't be much help. I'm sure there are thousands of container start/stop/restart scripts available.

Then, like I mentioned above, just "and" (`&&`) it to the end of your kiwix-zim command. (i.e. `./kiwix-zim.sh /opt/kiwix-zim/data/ -d && /opt/restart_container.sh` (of course, you'll need to adjust paths and names to match your setup, but you get the idea.)

**Comment by epheterson** [comment]
I can make a script to do it but I’m not sure how to have it run only if there’s an upgrade completed (I’d rather not restart the container every time). Does your script exit in such a way that the && with run only after an upgrade? IIRC an error in the script will cause the && to not run, otherwise it will always run.

**Comment by DocDrydenn** [comment]
Monitoring of the logs is a good idea.

That said, as you mentioned yourself, updates to ZIM(s) don't happen all that often. Why not just run the script once a month and let the container restart even if nothing was updated. I wouldn't call a "once-a-month" restart of the container as being excessive. Schedule the whole thing for after-hours/midnight and let it do its thing while you sleep.
